Repository cloudquery/cq-provider-digitalocean, pull requests merged in 2022-01, with the labels that each got.

#34 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/doc_validation.yml
  .github/workflows/golang_lint.yml
  .github/workflows/mock_test.yml
  .github/workflows/pr_title.yml
  .github/workflows/release.yml
  .golangci.yml
Labels: chore

#35 chore: Synced file(s) with cloudquery/.github
  .github/workflows/add_tags.yml
Labels: ignore-for-release

#36 feat: All migrations as files
  .github/workflows/test_migration.yml
  go.mod
  go.sum
  resources/provider/migrations/postgres/1_v0.3.0.down.sql
  resources/provider/migrations/postgres/1_v0.3.0.up.sql
  resources/provider/migrations/timescale/1_v0.3.0.down.sql
  resources/provider/migrations/timescale/1_v0.3.0.up.sql
  resources/provider/provider.go
  resources/provider/provider_test.go
  tools/migrations/main.go
Labels: feat

#37 feat: Upgrade SDK v0.7.0
  go.mod
  go.sum
Labels: feat
